[profile.goerli]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x26d74f09dc17b6239310aa27c213394acb2ae0ca'
]

[profile.bnbt]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x4077B8554A5F9A3C2D10c6Bb467B7E26Caf65ad9'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config